from playwright.sync_api import sync_playwright, expect


with sync_playwright() as p:
    browser=p.chromium.launch(headless=False)
    context=browser.new_context()
    page=context.new_page()
    page.goto("https://nikita-filonov.github.io/qa-automation-engineer-ui-course/#/auth/registration")
    mail=page.get_by_test_id('registration-form-email-input').locator('input')
    mail.fill('111@mail.ru')
    username=page.get_by_test_id('registration-form-username-input').locator('input')
    username.fill('username')
    password=page.get_by_test_id('registration-form-password-input').locator('input')
    password.fill('password')
    reg_but=page.get_by_test_id('registration-page-registration-button')
    reg_but.click()
    context.storage_state(path='browser-state.json')
    context=browser.new_context(storage_state='browser-state.json')
    page=context.new_page()
    page.goto('https://nikita-filonov.github.io/qa-automation-engineer-ui-course/#/courses')
    title=page.get_by_test_id('courses-list-toolbar-title-text')
    expect(title).to_be_visible()
    expect(title).to_have_text('Courses')
    result=page.get_by_test_id('courses-list-empty-view-title-text')
    expect(result).to_be_visible()
    expect(result).to_have_text('There is no results')
    page.wait_for_timeout(5000)
